# Generated by Django 4.0 on 2021-12-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
