# Generated by Django 4.0 on 2021-12-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_remove_imovel_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
